### ISSUE TITLE
POD error 

### ISSUE THREAD

**Issue by beppenmk** [cyansoft-dev/simple_downloader#1]
When I use this plugin on iOS, I receive a problem installing POD.
I rename the podspec file and now it's working.

`cp fl_downloader.podspec simple_downloader.podspec`

After this, the app compiles and works the first time but other times I receive this error

`Semantic Issue (Xcode): Use of undeclared identifier 'SimpleDownloaderPlugin'
/Users/AndroidStudioProjects/Flutter/flutterapp/ios/Runner/GeneratedPluginRegistrant.m:103:3`

This is my flutter doctor
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-x64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

`

**Comment by cyansoft-dev** [comment]
please update this plugin to v.0.0.2

**Comment by beppenmk** [comment]
now it s work! thanks
