### ISSUE TITLE
Exception : Connection closed while receiving data

### ISSUE THREAD

**Issue by SempaiEcchi** [cyansoft-dev/simple_downloader#2]
Hello! Chunked stream reader would throw connection closed while receiving data if user disconnects from network and retries the download. Did you expericene this issue, or is it something thats happening because of the host from where im downloading the file(s)?

**Comment by cyansoft-dev** [comment]
> Hello! Chunked stream reader would throw connection closed while receiving data if user disconnects from network and retries the download. Did you expericene this issue, or is it something thats happening because of the host from where im downloading the file(s)?

Hello, there is a possibility that the problem is with the host where you downloaded the file, because Chunked Stream reader only functions to cut values ​​based on the specified buffer size.
